### ISSUE TITLE
Avoid process leak by monitoring the pid that started the worker

### ISSUE THREAD

**Issue by seth** [chef/stats_hero#9]
stats_hero workers will leak (never get cleaned up) if the process that spawned them via `stats_hero_worker_sup:new_worker` crashes. When used to aggregate metrics for webmachine requests, this is rarely an issue since nearly all crashes will be trapped by a try/catch within the webmachine library and finish_request will still get called. In such a model, request processes that spawn_link for parallelization are especially vulnerable to abrupt crashes (via the link).

When spawning a worker, we should modify the API to accept the pid of the "parent" and have the worker monitor its parent.

When the worker receives a DOWN message from its parent, it should log the situation and exit (without sending data). The thinking being that applications may have special logic for when to  send so don't assume.

Bonus points for providing API to allow reparenting of a worker.

**Comment by markan** [comment]
Looked fixed in #10
